---
- hosts: linux
  tasks:
  - name: create multiple files
    file: 
      path: "{{ item }}"
      state: touch
    with_items:
    - /new/newfolder/test1.txt
    - /new/newfolder/test2.txt
    - /new/newfolder/test3.txt 
